### ISSUE TITLE
파이널 프로젝트 사전조사 관련 회의 - 20200629

### ISSUE THREAD

**Issue by DominKim** [DominKim/Final_project#2]
1. 적용될 알고리즘 선정
2. 데이터 전처리 방법

**Comment by nsh92** [comment]
1. 너무 어렵게 갈 필요 없이, 간단한 논리구조를 기반으로 뽑아낸 데이터를 보여주는 것 만으로도 우리가 의도하는 서비스를 만들 수 있다.
이렇게 간다 하면, 데이터는 딱 이렇게만 있으면 됨 : 자산,부채,자본 총계, 매출, 영업이익, 당기순이익 : 시계열일 필요 없고 가장 최근의 데이터면 됨+특별히 전처리할 일 없음

2. 여기서 1은 잠시 묻어두고, 뭔가 분석을 한다를 가정한다면,
(일단 데이터가 너무 짧다는 것도 함정)
2.1 0처리
2.1 행삭제
이렇게 두 옵션이 있는데,
0처리하면 레알로다가 쓸데없는 컬럼이 섞임 :  특히 그냥 제목 칼럼들
걍 행삭제를 추천함
행삭제를 한다면 2018년에 발생하였던 계정이나, 2019년에 발생하지 아니한 계정도 날라가지는 건데, 이런 계정은 재무구조에서 비연속적인 계정일 가능성이 매우 크므로 굳이 분석의 대상에 넣을 필요가 없다고 봄, 인사이트를 형성하는 데에 특별히 영향이 없는 데에 비하여 요구되는 수고는 꽤 클 것으로 예상됨

**Comment by DominKim** [comment]
2. 
 - 업종 != 업종명
 - 결산기준일이 다름
 - 보고서 종류 : 사업보고서 통일 ? 
 - 항목코드 : 국제기준, 국내기준, 신규회사 다름
![image](https://user-images.githubusercontent.com/61925841/85948527-5886a300-b98c-11ea-95a8-efcd7f76705c.png)
 - 항목명 : 중분류, 소분류, 세분류?
 - 결측치 중, 대분류가 아닌 항목명도 있음! : 중요하지 않은 것이 대부분이지만 회의 필요!


- 업종 != 업종명
> 두 변수 중 하나 선정해서 입력

- 결산기준일이 다름, 보고서 종류
> 사업보고서의 결산기준일이 회사마다 차이가 있으므로, 분기 및 반기 보고서로 대체

- 항목코드 : 국제기준, 국내기준, 신규회사 다름
> [포털](http://acct.fss.or.kr)에서 확인 후 내일 회의

- 항목명, 결측치 처리
> 각자 EDA 후 내일 회의 후 처리
